### ISSUE TITLE
POST ajax call and set cookie Does not work on local Docker with localhost  

### ISSUE THREAD

**Issue by retinafunk** [KaufmannDigital/KaufmannDigital.GDPR.CookieConsent#10]
After we tested the Component on a live and staging server we liked it and using it now.
But when trying to use it on a local development server ( running in docker container) I noticed that while I can see the CC GUI , when I click the Accept Button there is an XHR POST Error in Chrome Browser Dev Tools ( Network Tab) 

contact.html:2161 POST http://localhost:8098/api/kd-gdpr-cc 500 (Internal Server Error) 

and in the Network/Respose I see this NEOS / Flow Error:

**An exception occurred while executing 'INSERT INTO kaufmanndigital_gdpr_cookieconsent_domain_model_consentlogentry (persistence_object_identifier, consentdate, consentidentifier, userid) VALUES (?, ?, ?, ?)' with params ["fd5dd914-3659-4299-b6d0-9d8e22d047c1", "2020-06-24 10:17:18", "permanent", "5ef3282e86ffb"]:** 

I attached screenshots of the Dev Tools Errors: 

![DevTools - localhost_8098_en_contact html 24_06_2020 12_19_20](https://user-images.githubusercontent.com/6573881/85540135-ebcf7980-b616-11ea-9999-d00da4aa4aa7.png)
![DevTools - localhost_8098_en_contact html 24_06_2020 12_19_32](https://user-images.githubusercontent.com/6573881/85540141-ed00a680-b616-11ea-8f4f-aa45e5fd0189.png)

It would be really usefull to have the Component working in local docker containers. THanks in advance

**Comment by Nikdro** [comment]
Hi @retinafunk! 

Is this problem still relevant? I'm not able to reproduce this bug, but I have a first thought: Did you run `./flow doctrine:migrate` after the installation?   
It's not documented yet, but has to be done since the latest version.

**Comment by Nikdro** [comment]
Closing this issue due inactivity since June. Feel free to reopen, if needed.

**Comment by urbantrout** [comment]
I guess this is now fixed in v1 with https://github.com/KaufmannDigital/KaufmannDigital.GDPR.CookieConsent/commit/7698c7950d96e38e7528e7598e4a810312d477f2
