### ISSUE TITLE
Javascript String Template Literals in JS snippets are minified with errors 

### ISSUE THREAD

**Issue by retinafunk** [KaufmannDigital/KaufmannDigital.GDPR.CookieConsent#14]
I noticed a small bug when the JS snippets inserted in NEOS Inspector are minified, that Javascript String Template Literals in JS snippets are missing the Variables/ expression interpolations .
I mean the ${jsExpression} in const str = `  ... ${}  `

So for example. 

const mapSrc = `https://maps.google.de/maps?hl=de&q=${companyName}+${zip}+${city}&ie=UTF8&t=&z=17&iwloc=B&output=embed`;

is minfied to :

const mapSrc = `https://maps.google.de/maps?hl=de&q={}+{}+{}&ie=UTF8&t=&z=17&iwloc=B&output=embed`;

instead of :

const mapSrc = `https://maps.google.de/maps?hl=de&q=PERMANENT+40219+Duesseldorf&ie=UTF8&t=&z=17&iwloc=B&output=embed`;

A workaround was to use traditional JS String concat . SO this works: 

const mapSrc = 'https://maps.google.de/maps?hl=de&q='+companyName+'+'+zip+'+'+city+'&ie=UTF8&t=&z=17&iwloc=B&output=embed';

**Comment by Nikdro** [comment]
Thanks for you issue. Will check it and provide a Bugfix 🙂

**Comment by Nikdro** [comment]
Bugfix will be available in the next version. Will release it the next days.
