### ISSUE TITLE
Bug: Logging throws error 500 since version 3.1.0

### ISSUE THREAD

**Issue by Nikdro** [KaufmannDigital/KaufmannDigital.GDPR.CookieConsent#28]

**Comment by mchh** [comment]
@Nikdro First at all, thanks for your work on this great package. 
We have exactly this problem in one of our projects. Disabling logging is a workaround, but the main problem is, that the cookie isn't replaced in the users browser. Also, clearing cache and cookies manually don't solve the problem. You have to manually remove the cookie in dev tools to avoid the cookie banner on each page load. We can reproduce this behaviour on different environments (Win/Mac; Chrome, Edge Chromium, Firefox, Safari).

**Comment by Nikdro** [comment]
Hi @mchh! 

Sorry for my late response. Seems like I missed your answer here back in 2020. 
In later versions, we dropped support for logging, because other features (multisite/multi dimension/etc) made logging-data too big for the old DB-structure. 
We want to provide logging in future versions, again. But there is no exact plan right now. (Maybe we can make one together?!)

How are you using our package until today? Which Versions? Which features? Would it be an option for you, getting logging on a newer version?   
Otherwise: Do you have trouble on some old version until today? Then we can maybe help you getting this fixed with a bugfix-release on an older version. 

Please let me know, if we can help you (whatever) way :) You can also reach me via Slack! 

I'll close this issue until then, please don't hesitate to re-open it :) 

Niklas
