### ISSUE TITLE
JS Error in Backend

### ISSUE THREAD

**Issue by patricekaufmann** [KaufmannDigital/KaufmannDigital.GDPR.CookieConsent#40]
Problem:

In Neos Backend the object KD_GDPR_CC is not initialized, hence the following check in Initialize.js is throwing an error:
L21: `if (KD_GDPR_CC && document.cookie.indexOf(KD_GDPR_CC.cookieName) >= 0) {`

The check can be performed in the following way without throwing an error:
L21: `if (typeof KD_GDPR_CC !== 'undefined' && KD_GDPR_CC && document.cookie.indexOf(KD_GDPR_CC.cookieName) >= 0) {`

**Comment by Nikdro** [comment]
Fixed in V5 and just merged bugfix by @ru3fu5z in all 4.x Versions
