### ISSUE TITLE
Incompatibility with additional frontend caches

### ISSUE THREAD

**Issue by Sebobo** [KaufmannDigital/KaufmannDigital.GDPR.CookieConsent#8]
Due to the logic in Fusion to check whether to render the Consent configuration
Caches like Flowpack.FullPageCache and Varnish or others don't work properly
and one visitor influences the config for another one.

Also due to the uncached behaviour the page rendering is slower.

As discussed with @Nikdro in Slack I recommend moving the logic to Javascript
and solve any compatibility issue this way.

One of the other solutions for this https://github.com/wysiwyg-software-design/Wysiwyg.CookieHandling solves this from what I see by introducing a HTTP Component that would at least work with the FullPageCache but needs more work to configure properly.

**Comment by Nikdro** [comment]
Done with 2.2.0 🙂

**Comment by Sebobo** [comment]
Awesome thx!
Will test when I'm back from holiday

**Comment by vonloh** [comment]
with Flowpack.FullPageCache cache the fix works well for us
